create or replace 
trigger control_detalle_pedidos
AFTER INSERT OR UPDATE OR DELETE ON Contiene
FOR EACH ROW
BEGIN

IF INSERTING THEN
UPDATE PEDIDOS
set IMPORTET = IMPORTET + (:NEW.PRECIOT * :NEW.UDS)
WHERE CODIGOPEDIDO = :NEW.CODIGOPEDIDO;
END IF;

IF DELETING THEN
UPDATE PEDIDOS
set IMPORTET = IMPORTET - (:OLD.PRECIOT * :OLD.UDS)
WHERE CODIGOPEDIDO = :NEW.CODIGOPEDIDO;
END IF;

IF UPDATING THEN
UPDATE PEDIDOS
set IMPORTET = IMPORTET - (:OLD.PRECIOT * :OLD.UDS) + (:NEW.PRECIOT * :NEW.UDS)
WHERE CODIGOPEDIDO = :NEW.CODIGOPEDIDO;
END IF;

END;